# Read the documentation at https://github.com/thephpleague/flysystem-bundle/blob/master/docs/1-getting-started.md
flysystem:
    storages:
        public.uploads.storage:
            adapter: 'local'
            options:
                directory: '%kernel.project_dir%/public/%uploads_dir_name%'
        private.uploads.storage:
            adapter: 'local'
            options:
                directory: '%kernel.project_dir%/var/%uploads_dir_name%'
