# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    loaders:
        flysystem_loader:
            flysystem:
                filesystem_service: public.uploads.storage
    data_loader: flysystem_loader
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"

    filter_sets:

        user_preview_pic:
            filters:
                thumbnail:
                    size: [150, 150]
                    mode: outbound
                    allow_upscale: true


