roomView:
  path: /room/1
  methods: GET
  controller: App\Controller\RoomController::index

mainPage:
  path: /
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
  defaults:
    permanent: true
    keepQueryParams: true
    keepRequestMethod: true
    route: 'roomList'

roomList:
  path: /room
  methods: GET
  controller: App\Controller\RoomController::list

login:
  path: /login
  methods: GET|POST
  controller: App\Controller\SecurityController::login

logout:
  path: /logout
  methods: GET
  controller: App\Controller\SecurityController::logout