roomList:
  path: /room
  methods: GET
  controller: App\Controller\RoomController::list

roomSearch:
  path: /room/search
  methods: GET|POST
  controller: App\Controller\RoomController::search

roomCreate:
  path: /room/new
  methods: POST
  controller: App\Controller\RoomController::create

roomView:
  path: /room/{id}
  methods: GET|POST
  controller: App\Controller\RoomController::index

deleteMessage:
  path: /room/{id}/message/{messageId}
  methods: DELETE
  controller: App\Controller\RoomController::deleteMessage

attachment:
  path: /room/{id}/attachments/{attach_id}
  methods: GET
  controller: App\Controller\RoomController::getAttachment

mainPage:
  path: /
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
  defaults:
    permanent: true
    keepQueryParams: true
    keepRequestMethod: true
    route: 'roomList'

login:
  path: /login
  methods: GET|POST
  controller: App\Controller\SecurityController::login

logout:
  path: /logout
  methods: GET
  controller: App\Controller\SecurityController::logout

profile:
  path: /profile
  methods: GET|POST
  controller: App\Controller\SecurityController::profile


usersListApi:
  path: /api/users
  methods: GET
  controller: App\Controller\RoomController::usersQuery